### ISSUE TITLE
What type of data should we use?

### ISSUE THREAD

**Issue by sj602** [berndporr/py-ecg-detectors#10]
Hi! 
First of all, I'm really appreciated with this library. This saves my life!
I'm researching about detecting PVC by using R-signal.
I found my ECG data type is quite different with the one in example folder in this repository.
In example, there are thousands of real values,
In my data, there are integers values, which some of them are consecutive.
To use this library, How should I convert the data to?

[
<img width="488" alt="Screenshot 2020-05-03 23 48 18" src="https://user-images.githubusercontent.com/18183483/80917235-aae68180-8d98-11ea-80a1-95d8035acbbc.png">
](url)

**Comment by berndporr** [comment]
Best channel to use is Einthoven II so 2nd column. However in order to do that you need to know the sampling rate at which rate these rows have been generated and the conversion from the raw integer values to voltage. All this will be in the documentation of your dataset.

**Comment by sj602** [comment]
As my prof said, It's okay to use only V1 data for some reason.
So I'm gonna use only V1 and all data is sampled at 150khz.
Sorry I can't find the documentation because it's given by the prof and she also got it from medical engineering team.

For workaround, I just tried with my V1 csv data, and it seems to be working like below(black line colors at the R signal).

Even in this situation, do I need to convert the integers to voltage values for higher accuracy?
<img width="830" alt="Screenshot 2020-05-04 09 26 42" src="https://user-images.githubusercontent.com/18183483/80929764-7fd84e00-8de9-11ea-98ad-3df40208553e.png">

**Comment by berndporr** [comment]
Looking OK!
