### ISSUE TITLE
Detectors off?

### ISSUE THREAD

**Issue by skjerns** [berndporr/py-ecg-detectors#12]
Good work, and thanks for putting it together in a package!

I run it on a few test cases, however, all of the detectors fail and put the peaks at entirely wrong positions except for Engzee, do you know why this is the case? Do you recommend doing some filtering before or similar?

**Comment by berndporr** [comment]
What do you mean "entirely wrong positions"? Always 10 samples late? Or just random?

**Comment by skjerns** [comment]
You are right indeed, they are not entirely wrong, but sometimes consistently delayed. It just looked randomly when plotted overlayed on the ECG signal. I did some further analysis:

![image](https://user-images.githubusercontent.com/14980558/100747609-9330b380-33e2-11eb-9048-f1021047d9ad.png)

Histogramplot, 
y-axis: count of how many are in this bin
x-axis: wrong by how many seconds to best matching peak

```
~8h data with 256hz

Engzee: Perfectly like our training data
Hamilton: Quite randomly off, 
Christov: Relatively okay, but a bit off
SWT: consistently off by +-25 ms
Pan-Tompkins:  there seems to be a mismatch between R and S peak, a bimodal distribution appears
two_average: consistently off by ~70ms
```

**Comment by berndporr** [comment]
So they are all working correctly. They are all using causal filters for realtime processing. See:
https://github.com/berndporr/py-ecg-detectors#realtime--causal-processing

**Comment by berndporr** [comment]
If you are not familiar with causal signal processing have a watch here: https://www.youtube.com/playlist?list=PLxWwb-b9LnpCoo4GUR62sDT0-mzBt0VoV

**Comment by skjerns** [comment]
Ah, thanks! I did read that excerpt in the README, but I interpreted it such that this applies to "most other R detectors", and not the ones in the package. Sorry for that!

Then I have two questions:
1) Will the delay be constant across all cases, or will the delay be constant within one file?
2) In this case only Hamilton and Pan Tompkins are off, right?

**Comment by berndporr** [comment]
Well, is says "most R detectors". We've benchmarked basically all which are actively used.
Every detector will ideally introduce a constant delay independent of any other parameters but that has never been done systematically. The performance measure used in the papers is that a detector gets it right within quite a large time-window minus the constant delay. There is no good measure just now out there but I have a student doing her BEng thesis about this to come up with the perfect benchmark measure. Either way in your case the Hamilton / Pan Tompkins are off indeed. The rest look OK.

**Comment by berndporr** [comment]
BTW: The Engzee detector does an "argmax" on a small section of the ECG so looks backwards through a buffer. https://github.com/berndporr/py-ecg-detectors/blob/master/ecgdetectors.py#L358
Doesn't mean that it's always right but that it will deteriorate more binary when the rough search for a peak gets it wrong and then the argmax putputs a random timestamp.

**Comment by skjerns** [comment]
Thank's alot for the elaborate answer. I can work with this!

By the way, do you know any packages that perform post-detection correction? E.g. making plausible corrections to RRs, and/or removing outliers? Before I start implementing a paper.
