### ISSUE TITLE
local variable 'newM5' referenced before assignment

### ISSUE THREAD

**Issue by SorenJ89** [berndporr/py-ecg-detectors#13]
I have an ecg recording which gives the error:

`  File "C:\toolkits\Anaconda3\lib\site-packages\ecgdetectors.py", line 310, in engzee_detector
    MM.append(newM5)
UnboundLocalError: local variable 'newM5' referenced before assignment
`

It seems like the newM5 variable is defined in one clause and used in another:
```
           if i < 5*self.fs:
                M = 0.6*np.max(low_pass[:i+1])
                MM.append(M)
                if len(MM)>5:
                    MM.pop(0)

            elif QRS and i < QRS[-1]+ms200:

                newM5 = 0.6*np.max(low_pass[QRS[-1]:i])

                if newM5>1.5*MM[-1]:
                    newM5 = 1.1*MM[-1]

            elif QRS and i == QRS[-1]+ms200:
                MM.append(newM5)
                if len(MM)>5:
                    MM.pop(0)    
                M = np.mean(MM)  
```

**Comment by berndporr** [comment]
Hi, that should be fixed. newM5 is the new current threshold but that's extracted from the 1st QRS complex. Setting it now to False and then it's only saved once we have one. Committed on git.
