### ISSUE TITLE
Stationary Wavelet Transform detector problem

### ISSUE THREAD

**Issue by darkcurrent** [berndporr/py-ecg-detectors#14]
"Stationary Wavelet Transform detector" works really great but I think there is some auto thresholding problem with it. When some disturbances occur in the ECG waveform the remaining normal R waves can not be detected for a while.

If this problem can be solved I think this is the best way to detect R waves.

For example in the attached pictures you can easily see what I mean.

_(orange lines: swt_detector, green lines: pan_tompkins_detector, red lines: two_average_detector, blue lines: biosppy's default detector)_
![ecg1](https://user-images.githubusercontent.com/6089944/111064426-0c9d6f00-84c5-11eb-98d6-3563c8dd9f75.png)
![ecg2](https://user-images.githubusercontent.com/6089944/111064428-0d360580-84c5-11eb-965e-db1c06574440.png)

**Comment by berndporr** [comment]
Feel free to improve it and send a pull request.
