### ISSUE TITLE
wqrs

### ISSUE THREAD

**Issue by Yoav11** [berndporr/py-ecg-detectors#15]
Hi,

Thanks for making this package! I'm currently using it for various tasks and it saves me a ton of time.

I would like to contribute and add a wqrs detector (W Zong’, GB Moody), is this repo still being maintained ? is it worth me adding a PR ? 

Thanks 😄

**Comment by berndporr** [comment]
It's being maintained and yes please submit a PR.

**Comment by Yoav11** [comment]
Great thanks, please see #16
