### ISSUE TITLE
Issue with Engzee detector

### ISSUE THREAD

**Issue by RaviDurbha** [berndporr/py-ecg-detectors#17]
Hello,

 For almost eight months I have been using py-ecg-detectors library specifically Engzee (Engelse and Zeelenberg) detector for detecting R-peaks in EKG signals. But from last week (4th Nov 2021), I observed that this detector is throwing an error r_peaks as [], an empty vector for different lengths of EKG data recorded. 

Other detectors such as Pan-Tompkins, SWT are able to detect R-peaks but at wrong places. 

Looking forward for your help in resolving the issue with Engzee detector as this was detecting very accurately the R-peaks. 

I am using Windows 10 system to run the code and Pycharm python IDE.

Thanks,
Ravi

**Comment by berndporr** [comment]
Since the detector hasn't been changed for more than a year I suspect that one of your libraries is buggy. Check which dependent library has been updated on 4th Nov. You find all dependencies in the setup.py.

**Comment by berndporr** [comment]
closing it now because of lack of feedback.
