### ISSUE TITLE
Detector with window local maxima

### ISSUE THREAD

**Issue by mscheltienne** [berndporr/py-ecg-detectors#18]
I found this R-peak detector in MATLAB that looks interesting, and maybe I am mistaken, but I don't find its equivalent in Python: http://www.librow.com/articles/article-13
Would it be worth adding?

**Comment by berndporr** [comment]
Basically it's a highpass filter and then doing max detection. For example the two_average_detector does a similar thing. A highpass filter is btw not the greatest idea as it amplifies the noise in the ECG and for that reason usually a bandpass filter is used. What you suggest is sort of how it's done in a quick/dirty way. Plus detecting maxima is a very debatable method as it's much better to set a threshold where the signal passes through with max speed and not trying to detect peaks where there might be noise (i.e. multiple peaks).

**Comment by berndporr** [comment]
So, given that it's not based on a peer reviewed paper the answer is: no. Sorry!

**Comment by mscheltienne** [comment]
I agree the approach described is simplistic and not peer-reviewed. However, it is a bit more than a simple max detection with an iterative/culling process to better detect the R-peaks.
In that regard, I would find an implementation of this method in python very useful to compare its performance against more advance methods.
This is the most useful aspect of this library IMO, quick and easy comparison between algorithms. It took me less than 10 minutes to try all the implementation you provide and decide on one for my specific use case thanks to the simple API design.

**Comment by berndporr** [comment]
I run a class of 400 DSP students where they had to come up with their own R peak detector with similar instructions. Most of them work so I could add about 100 of them here. There is no point adding all different kind of detectors. One could add 100s doing different variations just bloating this module.
The main purpose of this library is that it's grounded in science and that means based on peer reviewed material and not some hack from the web. We have been working on a paper for a while to benchmark them where we refer to the peer reviewed works here. At the moment it's more urgent to find a proper performance measure as just now everybody claims theirs is great -- even the 8 peer reviewed. Of course all of my DSP students claim theirs is great as well -- of course they should as they did a great job.
