### ISSUE TITLE
panPeakDetect function error found

### ISSUE THREAD

**Issue by augelloantonio** [berndporr/py-ecg-detectors#20]
Hi, thank you for your library, in first. I really appreciate your work.
I am a researcher and I am doing some tests on a Pam Tompkins derived algorithm I developed and I am using your Pam Tompkins algorithm to do some tests on false positive and false negative to validate the effectiveness of my algorithm.
Unfortunately I found an error calling the function "panPeakDetect" itself, because I do my own filtering method.
This happened while I was running my testing on the sample 104 of the MIT Arrhythmia DB.

The error code is:
ecgdetectors.py", line 590, in panPeakDetect
    missed_peak = missed_section_peaks2[np.argmax(detection[missed_section_peaks2])]
TypeError: list indices must be integers or slices, not list

The problem is that you are passing a list (missed_section_peaks2) to find the signal index of what is in missed_section_peaks2.

My solution is to iterate over that list as follow returning a list containing only the signal to pass to np.argmax:

```
if len(missed_section_peaks2)>0:     
                                arg_max = []
                                for m in missed_section_peaks2:
                                    arg_max.append(detection[m])
                                missed_peak = missed_section_peaks2[np.argmax(arg_max)]
                                missed_peaks.append(missed_peak)
                                signal_peaks.append(signal_peaks[-1])
                                signal_peaks[-2] = missed_peak 
```

This way missed_section_peaks2 will contain the max argument in that section.
Not sure if it is correct, but it works now.

Again thank you for your precious work.

Kindly,
Antonio Augello

**Comment by berndporr** [comment]
Hi Antonio,
thanks for flagging this up. Do you have a test case were this fails? Looks like that this code segment is never reached by any of the detectors used here. I've messed around a bit with the code to provoke it but no luck. Do you have a code fragment where this happens? Might be also a good idea for a unit test.
Best,
/Bernd

**Comment by augelloantonio** [comment]
Hi,
I don't have anymore the configuration/analysis file. I was using this while doing test case on the "MIT Arrhythmia" DB, i don't remember properly which dataset caused the error, but will test it again asap I have few moments.

Regards,
Antonio

**Comment by berndporr** [comment]
That's great. Thanks!

**Comment by berndporr** [comment]
I've created a bugfix branch and worked in your fix. The library needs tons of unit tests anyway. Tempted to advertise it as an MSc project next year but if you happen to create a test case that would be very much appreciated.

**Comment by augelloantonio** [comment]
Hi Bernd,
Sorry I completely forgot about replacing the error, have been so busy lately.
I did run again the code into an analyzer I build to test all of the 44 sample of the MIT-BIH NSR & ARRHYTHMIA DB, the sample where the error occurs also on sample n.100.

After a better reading and a better check I can say following:
- My previous code was wrong because what do you need is to get the max value (amplitude mV) of the "missing peaks list", so first you need to build the "amplitude" list, the correct way will be  -> signal_missed = [detection[i] for i in missed_section_peaks2];
-  get the index of the max of this list -> index_max = np.argmax(signal_missed);
- get the missed peak -> missed_peak = missed_section_peaks2[index_max]

What I was doing instead with my previous solution was get the max index peak from missed_section_peaks2, that is not correct because we need the max amplitude, not the max index peak.

The correct solution would be:
if len(missed_section_peaks2)>0:         
                                signal_missed = [detection[i] for i in missed_section_peaks2]
                                index_max = np.argmax(signal_missed)
                                missed_peak = missed_section_peaks2[index_max]
                                missed_peaks.append(missed_peak)
                                signal_peaks.append(signal_peaks[-1])
                                signal_peaks[-2] = missed_peak

Feel free to discuss about.

Antonio

**Comment by berndporr** [comment]
Hi Antonio,
that all looks good. Thanks for delving deeply into it. Actually the new visual code directly threw the original code as an error.
I've also absorbed the if clause into the range() command of the loop to speed things up.
