### ISSUE TITLE
Superfluous and confusing increment of loop counter in hamilton_detector()

### ISSUE THREAD

**Issue by mj-64** [berndporr/py-ecg-detectors#23]
In ecgdetectors.py, function hamilton_detector, line 140, the loop counter i is incremented (i += 1).

This has no effect, because it is the last loop statement and i is reassigned by the for loop.

Try this in python to see:

    for i in range(10):
        print(i)
        i += 1
        print(i)

**Comment by berndporr** [comment]
Fixed. Thanks for pointing it out.
