### ISSUE TITLE
Checking the length of the wrong array on hamilton_detector()

### ISSUE THREAD

**Issue by purpl3F0x** [berndporr/py-ecg-detectors#24]
Here the check should probably be `lenght(s_pks)`
https://github.com/berndporr/py-ecg-detectors/blob/7a1ca569190a4c17885089c97480efd114c64120/ecgdetectors.py#L113

**Comment by berndporr** [comment]
That's indeed a bug and using deque as suggested over there https://github.com/neuropsychology/NeuroKit/pull/947/commits/b36558803894448cacedc53d23d38b5dfe30fb98 makes sense. The pop commands are super slow indeed.

**Comment by purpl3F0x** [comment]
I think the issue can be closed now.
