### ISSUE TITLE
Error when pip installing

### ISSUE THREAD

**Issue by cbrnr** [berndporr/py-ecg-detectors#3]
When I do `pip install py-ecg-detectors` I get the following error:

```
ERROR: Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/usr/local/templates'
Consider using the `--user` option or check the permissions.
```

I think this is caused by the `data_files` list in `setup.py`. I think you should use `package_data` instead of `data_files` to include this folder in the `site-packages` package structure (https://docs.python.org/3.8/distutils/setupscript.html#installing-package-data).

**Comment by cbrnr** [comment]
I think fixing this issue requires restructuring the code into a package instead of distributing the two modules `ecgdetectors` and `hrv`. Would you be OK with such a change? This means that you can't `import ecgdetectors` anymore, but you'd need to `from py-ecg-detectors import ecgdetectors`. Provided you want to call your package `py-ecg-detectors`, which is a bit unwieldy and maybe a shorter name would be more appropriate.

**Comment by berndporr** [comment]
Do you run this command as a normal user or as root? If you run it as a normal user then that's expected behaviour. Works fine here on Ubuntu LTS.
For root/sudo it's correct to be in:
```
  /usr/local/lib/python3.6/dist-packages/ecgdetectors.py
  /usr/local/lib/python3.6/dist-packages/hrv.py
  /usr/local/lib/python3.6/dist-packages/py_ecg_detectors-0.9.4.dist-info/DESCRIPTION.rst
  /usr/local/lib/python3.6/dist-packages/py_ecg_detectors-0.9.4.dist-info/INSTALLER
  /usr/local/lib/python3.6/dist-packages/py_ecg_detectors-0.9.4.dist-info/METADATA
  /usr/local/lib/python3.6/dist-packages/py_ecg_detectors-0.9.4.dist-info/RECORD
  /usr/local/lib/python3.6/dist-packages/py_ecg_detectors-0.9.4.dist-info/WHEEL
  /usr/local/lib/python3.6/dist-packages/py_ecg_detectors-0.9.4.dist-info/metadata.json
  /usr/local/lib/python3.6/dist-packages/py_ecg_detectors-0.9.4.dist-info/top_level.txt
  /usr/local/templates/template_250hz.csv
  /usr/local/templates/template_360hz.csv
```
For a normal user it's installed in your home dir:
```
  /home/bp1/.local/lib/python3.6/site-packages/__pycache__/ecgdetectors.cpython-36.pyc
  /home/bp1/.local/lib/python3.6/site-packages/__pycache__/hrv.cpython-36.pyc
  /home/bp1/.local/lib/python3.6/site-packages/ecgdetectors.py
  /home/bp1/.local/lib/python3.6/site-packages/hrv.py
  /home/bp1/.local/lib/python3.6/site-packages/py_ecg_detectors-0.9.9.dist-info/DESCRIPTION.rst
  /home/bp1/.local/lib/python3.6/site-packages/py_ecg_detectors-0.9.9.dist-info/INSTALLER
  /home/bp1/.local/lib/python3.6/site-packages/py_ecg_detectors-0.9.9.dist-info/METADATA
  /home/bp1/.local/lib/python3.6/site-packages/py_ecg_detectors-0.9.9.dist-info/RECORD
  /home/bp1/.local/lib/python3.6/site-packages/py_ecg_detectors-0.9.9.dist-info/WHEEL
  /home/bp1/.local/lib/python3.6/site-packages/py_ecg_detectors-0.9.9.dist-info/metadata.json
  /home/bp1/.local/lib/python3.6/site-packages/py_ecg_detectors-0.9.9.dist-info/top_level.txt
  /home/bp1/.local/templates/template_250hz.csv
  /home/bp1/.local/templates/template_360hz.csv
```
I reckon there is something strange going on in your settings. As you see only as root it goes into `/usr/local/templates/` and for that you need root permissions. Otherwise it goes into '/home/bp1/.local/templates/'.

Did you run pip as root or as a normal user?

**Comment by berndporr** [comment]
PS: my recent version of pip3 automatically detects if it's run as root or normal user and then installs it to either the user dir or the global one. As the command suggests as a normal user you can tell it that explicitly with the `--user` option. Under Windows always needed.

**Comment by cbrnr** [comment]
I run it as a normal user, but the problem is that `/usr/local/` is not writeable. In my opinion, there shouldn't be a `templates` folder here, because this folder belongs only to the `py-ecg-detectors` package.

What should really happen is that because the files in the `templates` folder are required by some functions of the package, this folder should be included with the package inside the `site-packages` folder structure. But for this to work, there needs to be a root package, which currently doesn't exist.

**Comment by cbrnr** [comment]
Even with `--user` I'd prefer not to have these files in `.local/templates`, but in the user site-packages folder under the package folder.

**Comment by cbrnr** [comment]
The `pyreadstat` package had the same issue (it wanted to copy two files to a non-writeable location), maybe you can check how this was solved there (https://github.com/Roche/pyreadstat/issues/23).

**Comment by berndporr** [comment]
I'm reluctant to make any massive changes to the package. After all you can just use `--user` to make it install in your local dir and it's all sorted. I don't want to break a lot of installations of the package as it's very popular and it's more a matter of "purity" to have everything in the site packages. It does work for both user and root admin so I leave that for version 2.0. For now I keep it as it is. Either way thanks for you help!

**Comment by cbrnr** [comment]
Sure, but this solution is basically a hack and I'm reluctant to install packages that don't follow packaging standards (it's not just about purity). I understand that you don't want to change that immediately, but it might be a good idea to follow some basic packaging guidelines as outlined here for example: https://python-packaging.readthedocs.io/en/latest/minimal.html - which means that there should be at least a folder (package) containing all modules.

Anyway, I'm happy to help, let me know if you'd want me to make a PR for the restructured code (for release 2.0).

**Comment by berndporr** [comment]
No thanks. Not sure which syntax fixing program you have used but I'm just fixing bugs introduced by the tidying up. See my latest commits. It's not just style but it actually changed code in an unexpected way. The two benchmark scripts crash now. I've just checked out the versions before the massive code happened. Either way I'm happy to commit coding style issues but amongst the large number of style changes are a couple actual code changes which cause crashes. Basically we have now beautiful looking code which I no longer trust. I'll revert your commits for now and then cherry pick the package issues which were the only really issue. I certainly prefer bug free code against good looking code. I'm very busy these days and that cost me a couple of hours comparing the code now via diff by hand and running the test scripts. After all they act as unit tests and they crash so no good. Sorry but that's too risky just now and I have no time to debug your patches.

**Comment by AmroAbdrabo** [comment]
I get No module named 'ecgdetectors' when I do "import ecgdetectors" even though that is what is written on berndporr's github tutorial on ecgdetectors. Is there a fix for this?

**Comment by berndporr** [comment]
Did you install the module?

**Comment by AmroAbdrabo** [comment]
Yes I did 
!pip3 install --user py-ecg-detectors
import numpy as np
import matplotlib.pyplot as plt
import pathlib
from ecgdetectors import Detectors

inside jupyter notebook

**Comment by berndporr** [comment]
```
pip3 install --user py-ecg-detectors
Collecting py-ecg-detectors
  Using cached py_ecg_detectors-1.0.2-py3-none-any.whl (13 kB)
Requirement already satisfied: gatspy in /usr/local/lib/python3.8/dist-packages (from py-ecg-detectors) (0.3)
Requirement already satisfied: scipy in /usr/lib/python3/dist-packages (from py-ecg-detectors) (1.3.3)
Requirement already satisfied: numpy in /usr/lib/python3/dist-packages (from py-ecg-detectors) (1.17.4)
Requirement already satisfied: pywavelets in /usr/local/lib/python3.8/dist-packages (from py-ecg-detectors) (1.1.1)
Installing collected packages: py-ecg-detectors
Successfully installed py-ecg-detectors-1.0.2
python3
Python 3.8.5 (default, Jul 28 2020, 12:59:40) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from ecgdetectors import Detectors
>>> 
```
I guess there is something wrong with your jupyter notebook.

**Comment by AmroAbdrabo** [comment]
Okay it worked when I changed pip3 into pip. But yeah must be a problem in the settings of Jupyter I assume. Thank you

**Comment by careen28** [comment]
I'm trying to install the module using jupyter notebook and im facing this problem

![error](https://user-images.githubusercontent.com/127662165/224540971-4a2b5a95-27be-4a54-8f43-2137977a2cc3.png)

**Comment by berndporr** [comment]
It seems to be a windows problem. Please open a new issue and not append it to a closed one. Also instead of screenshots please use quotable text. Otherwise I need to type it out again.
