### ISSUE TITLE
The example data is missing.

### ISSUE THREAD

**Issue by roohy466** [berndporr/py-ecg-detectors#7]
Hi Thanks for your code.
I tried to use use usage_example.py but it seems installing it via pip does not download the example data  or even create any directory related to the package! Is it fine? or I should download manually the data set.

the error is like this:

C:\ProgramData\Miniconda3\lib\site-packages
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-14-ab16b4caf5da> in <module>
      8 current_dir= ecgdetectors .__file__
      9 print(path)
---> 10 current_dir = pathlib.Path(__file__).resolve()
     11 print(current_dir)
     12 example_dir = current_dir.parent/'example_data'/'ECG.tsv'

NameError: name '__file__' is not defined

Best Rouhi

**Comment by berndporr** [comment]
If you install via pip you won't even get the usage_example.py. That's just on git. I've checked and it's not in the package.
```
Uninstalling py-ecg-detectors-1.0.0:
  /usr/local/lib/python3.6/dist-packages/__pycache__/ecgdetectors.cpython-36.pyc
  /usr/local/lib/python3.6/dist-packages/__pycache__/hrv.cpython-36.pyc
  /usr/local/lib/python3.6/dist-packages/ecgdetectors.py
  /usr/local/lib/python3.6/dist-packages/hrv.py
  /usr/local/lib/python3.6/dist-packages/py_ecg_detectors-1.0.0.dist-info/DESCRIPTION.rst
  /usr/local/lib/python3.6/dist-packages/py_ecg_detectors-1.0.0.dist-info/INSTALLER
  /usr/local/lib/python3.6/dist-packages/py_ecg_detectors-1.0.0.dist-info/METADATA
  /usr/local/lib/python3.6/dist-packages/py_ecg_detectors-1.0.0.dist-info/RECORD
  /usr/local/lib/python3.6/dist-packages/py_ecg_detectors-1.0.0.dist-info/WHEEL
  /usr/local/lib/python3.6/dist-packages/py_ecg_detectors-1.0.0.dist-info/metadata.json
  /usr/local/lib/python3.6/dist-packages/py_ecg_detectors-1.0.0.dist-info/top_level.txt
  /usr/local/templates/template_250hz.csv
  /usr/local/templates/template_360hz.csv
```
So not sure where you got the usage example from except from git. The example data is on git where it should be.

**Comment by roohy466** [comment]
OK! I have downloaded "usage_example.py" from the git and it gave me the error that i mentioned above. Therefore as you mentioned I have to download the example data set manually and feed it to "usage_example.py".  problem solved! Thanks

**Comment by berndporr** [comment]
Errr. Which "error"?
