### ISSUE TITLE
Pan-Tompkins slow execution

### ISSUE THREAD

**Issue by IoannisStournaras** [berndporr/py-ecg-detectors#8]
Hi. Thanks for the code.
I was benchmarking the performance of different detection algorithms on MIT-BIH database and I noticed that Pan-Tompkins and Two Moving Average execution was rather slow.

Both algorithms depend on the MWA function to calculate the moving window average. I benchmarked the performance of two different moving average functions with the following results:

*Start benchmark!!!* 
Execution time in seconds using original moving average function: 
 3.5515489461900143

Execution time in seconds using moving average with convolution: 
 0.018413547830014067

Execution time in seconds using moving average with cumulative sum: 
 **0.005457540920051542**

Best, 
Ioannis

**Comment by berndporr** [comment]
Thanks! Do you have a pull request for it?

**Comment by berndporr** [comment]
thanks! I've merged it. Looking good.
